dist: trusty
sudo: false
language: python
python: '3.6'
install:
- pip install sphinx
- cd ..
- pwd
- ls -la
- git clone https://github.com/python-doc-ja/py35.git py35
- git clone --depth=5 -b intl-3.5 https://github.com/python-doc-ja/cpython-doc-intl.git
  cpython
- cd cpython/Doc
- ln -s ../../py35-locale locale
- ls -lF locale
- sphinx-build -j4 -D language=ja -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1
  -E -d build/doctrees . ../../py35
script:
- cd ../../py35
- git config user.email "travis-build-bot@example.com"
- git config user.name "Autobuild bot on Travis-CI"
- git pull origin master
- git add .
- git commit -a -m "update html"
- git push --quiet "https://${GH_TOKEN}@github.com/python-doc-ja/py35.git" master:master

GH_TOKEN:
  secure: Y3ZVFY9JBG9a92/TuD+BGnyz6ygdmR/NTXoXXhw5i6oMlkMeev7Ja11Fqc4rQo8gY7g9ghoYiQwN7gaAimnW+RWx01XBQOMc56gCLfKlr8wTqsM+9R3OErALq7NFbOpC8ZCOiVGJV2JXFxJ3zaBvVxjoNZFQSVbhEmx7CSDJJu9R9um/d363rZsdQbcEYrVHdiHUvSjRNRbSZud/XFlYY7AwEw2hoehX2T31Etzw2A3k+CPNKBYkoX1rRHijUfzlx+rxYaqeiHUYhF9frta00/9xEXi1A8hox5Co+HG3eUTMIaOqCH0kvD+jg+ss8Ms/MvJ1vvKZIrRtpvGhE5xH8TxgOj+nO0Ox8dE8TaUtXifDDttlYavWkI0iIlyJ4VIt1lldTCc5DV0V27nvZUyMbSUE8Bxxe2nn61u10HokCSuaZ/eHMUJv5zpCisrl01mzIj9QQ1tQlAzlM2lBeXh5D0u6IBLZBViAV7uKWludMDx+cQRy7cTUNsuSfCWHqG/XQHZlpq5Y6L15Xfl/c9E4b85ooJRLXyOiAD53Km2v8SKzRF4uyHBLnPsev5cwvC1ib1l44aW2G/IaF7fi4rlJf6csGkvT5YJTI7UYH8j3JeF4c8GeAXMFMalsQ/kvolY9EgoO1bTxFiSzEZjCccBlMDFBA46SMFmq52d8Mv6z1e0=
