dist: trusty
sudo: false
language: python
python: '3.6'
install:
- pip install sphinx==1.4.9
- cd ..
- pwd
- ls -la
- git clone https://github.com/python-doc-ja/py35.git py35
- git clone --depth=5 -b intl-3.5 https://github.com/python-doc-ja/cpython-doc-intl.git cpython
- cd cpython/Doc
- ln -s ../../py35-locale locale
- ls -lF locale
- sphinx-build -j4 -D language=ja -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . ../../py35
script:
- ./update_github_pages.sh

env:
  global:
    secure: "jDUJp2OuVyRWxuEJIxKMNouA1eh/B8xdQsfua6+C4K2nNYbT7XyVlPg3K8ZsFT9udN8/k/n8fyj1rXZJa8yuS4D0SqrU3xHp/kwbt5qx1U/G4+Ts/GPflk0SkGkK3pfic3TWjMRZIDHvVch3+Cjx29NCEe3f4qQZ5s4Pk+xy+iMnyCgVapvpranXZjZggTBkiw9t23bqGfbbxjOEvV9UKmHM4QFi7vgui04XUp8D+GZUg6dyrkMTyMu0XxazibFWfPAzXIqTZ4XpbSs+wkwZq0FohlnLgM59f7+45ByLSibTkloB10upfeGuH9UHMevm2t8XQc2Vay3IJOEJTu5sayBjGJB7lgP/s6T0/ZL7QOl4++XHX0ODOuwB7u0/hGBeXLhIN1w0JThoM25AZROOjhD4jGZdrRiqmbkUO19srMh3wU3ZViBVoPVG9GtdTL5USVjoBxR3e8gUZ1RkJogoqWjX3YIvBG2lGr/6xEV04o7t+G5pxTMaglfX49mFkVv+N57l5s6NDnEIV4ibrc6ns1aeiCmOb0Q6eUvAFbMaWS5Pben6UL8As4sFQSDrmnS5c7xc8rJYWSJihK2svdpkUvTLadDRaQ65bOzkekRQJnzqGRw9AyeQpCjLggmbFEzSeuW42gnJ1thbckLHJ8Se0ys0SocLN90QHG57nOY24u8="
